apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-node
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: worker-node
  template:
    metadata:
      labels:
        app: worker-node
    spec:
      containers:
      - name: worker
        image: ubuntu:latest 
        command: ["/bin/bash", "-c", "sleep infinity"] 