filebeat.inputs:
    - type: filestream
      paths:
      - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

    http.enabled: true
    http.port: 5066

    output.elasticsearch:
      hosts: ['http://172.21.212.175:31358/']
      path: "/es/"
      username: "admin"                 
      password: "Complexpass#123"                 
      index: "filebeat-logs-%{+yyyy.MM.dd}"

    setup.template.name: "filebeat"      
    setup.template.pattern: "filebeat-logs-*"  

    logging:
      level: info
      to_files: true
      files:
        path: /var/log/filebeat
        name: filebeat
        keepfiles: 7
        permissions: 0644

    