filebeat.inputs:
- type: container
  paths:
    - /var/log/containers/*.log
  processors:
    - add_kubernetes_metadata:
        in_cluster: true

output.prometheus:
  host: "http://172.21.212.175:31090/"  