apiVersion: v1
kind: PersistentVolume
metadata:
  name: filebeat-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/d/Dissertation/Project/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat-pvc
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi