apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: sock-shop
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

    http.enabled: true
    http.port: 5066

    output.file:
      path: "/tmp/filebeat"
      filename: filebeat
