apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
spec:
  replicas: 3  # One pod for each worker node
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
        - name: k6
          image: loadimpact/k6:latest
          command: ["k6", "run", "/scripts/load-test.js"]
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts
